
inherit_from: configs/learning_based/noise_large/ours.yaml
data:
  class: ['']
  path: data/demo/shapenet_chair
train:
  out_dir: out/demo_shapenet_large_noise
test:
  model_file: https://s3.eu-central-1.amazonaws.com/avg-projects/shape_as_points/models/ours_noise_025.pt